name: Notify Slack on .md file creation

on:
  push:
    paths:
      - '**/*.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          REPO_NAME=${{ github.repository }}
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$')
          if [ -n "$FILES" ]; then
            for FILE in $FILES; do
              curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$COMMIT_AUTHOR"' 님이 '"$REPO_NAME"' 에 '"$FILE"' 을 추가하셨어요! 확인해보세요!"}' $SLACK_WEBHOOK_URL
            done
          fi
