name: Notify Slack on .md file creation

on:
  push:
    paths:
      - '**/*.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get commit details
        id: commit_info
        run: |
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.md$')" >> $GITHUB_ENV

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            for FILE in $CHANGED_FILES; do
              PAYLOAD=$(jq -n --arg author "$COMMIT_AUTHOR" --arg repo "${{ github.repository }}" --arg file "$FILE" '{text: "\($author) 님이 \($repo) 에 \($file) 을 추가하셨어요! 확인해보세요!"}')
              curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
            done
          fi
