name: Notify Slack on .md file creation

on:
  push:
    paths:
      - '**/*.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get commit details
        id: commit_info
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "AUTHOR=${AUTHOR}" >> $GITHUB_ENV

      - name: Find added .md files
        id: find_files
        run: |
          ADDED_FILES=$(git diff --diff-filter=A --name-only HEAD~1 HEAD | grep '\.md$' || true)
          echo "ADDED_FILES=${ADDED_FILES}" >> $GITHUB_ENV
          echo "Added files: $ADDED_FILES"

      - name: Notify Slack
        if: env.ADDED_FILES != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          AUTHOR: ${{ env.AUTHOR }}
          ADDED_FILES: ${{ env.ADDED_FILES }}
        run: |
          for FILE in $ADDED_FILES; do
            PAYLOAD=$(jq -n --arg author "$AUTHOR" --arg file "$FILE" '{text: "방금 \($author) 님이 \($file) 을 생성하셨어요! 확인해보세요!"}')
            curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
          done
